FROM php:8.2-apache AS pandoc

RUN apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
		pandoc \
		jq \
		awscli \
	&& apt-get clean

COPY pandoc/* /var/www/html/

RUN mkdir \
		/var/www/datatmp \
		/var/www/html/imgs \
	&& chown www-data:www-data \
		/var/www/datatmp \
		/var/www/html/imgs

COPY docker/pandoc-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENTRYPOINT [ "/usr/bin/docker-entrypoint.sh" ]

CMD [ "apache2-foreground" ]

FROM debian:12.5 AS cron

RUN apt-get update \
	&& apt-get install -y --no-install-suggests --no-install-recommends \
		cron \
	&& apt-get clean

COPY pandoc/cleanup-old-files /etc/cron.daily

RUN chmod 755 /etc/cron.daily/cleanup-old-files

CMD ["cron", "-f"]

		