FROM node:22

WORKDIR /app

COPY livepoll/* /app/

RUN npm install

COPY docker/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENTRYPOINT [ "/usr/bin/docker-entrypoint.sh" ]

CMD ["node", "/app/index.js"]
